create table patent(
 id VARCHAR(40) NOT NULL,
 public_date DATE,
 apply_no VARCHAR(40),
 apply_date DATE,
 patent_no VARCHAR(40),
 patent_name VARCHAR(200),
 primary_class_no TEXT,
 class_no TEXT,
 applier TEXT,
 author TEXT,
 abstract_content TEXT,
 protect_item TEXT,
 priority_item TEXT,
 patent_families TEXT,
 code VARCHAR(20),
 original_no VARCHAR(40),
 p_address VARCHAR(200),
 agency VARCHAR(200),
 agent VARCHAR(100),
 examinant VARCHAR(40),
 issue_date DATE,
 international_apply VARCHAR(100),
 international_public VARCHAR(100),
 import_date DATE,
 abstract_img_path VARCHAR(100),
 europe_primary_class_no TEXT,
 europe_class_no TEXT,
 state_primary_class_no TEXT,
 state_class_no TEXT,
 p_path VARCHAR(100),
 page_num SMALLINT(3),
 country_code VARCHAR(40),
 patent_type VARCHAR(40),
 apply_sources VARCHAR(100),
 p_references TEXT,
 category_class VARCHAR(40),
 PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;